import type { NeuralCoreRuntimeInput } from "neural-system-ui";

import type { ShowcaseMessages } from "../../i18n/showcase-i18n.types";
import { createShowcaseRuntime } from "./showcase-runtime.factory";
import type { ShowcaseScenarioDefinition } from "./showcase-scenario.types";

const createMixedRuntime = (messages: ShowcaseMessages): NeuralCoreRuntimeInput => createShowcaseRuntime(
  "mixed",
  messages,
  2_800,
  [
    {
      id: "mixed-request-received",
      kind: "request-received",
      status: "processing",
      atMs: 0,
      durationMs: 600,
      entityId: "api-gateway",
      clusterId: "experience",
      routeId: "web-app-to-api-gateway",
      pathwayId: "customer-request",
      title: messages.narrative.requestReceived,
    },
    {
      id: "mixed-inventory-delayed",
      kind: "warning-raised",
      status: "warning",
      atMs: 600,
      durationMs: 900,
      entityId: "inventory-service",
      clusterId: "transactions",
      routeId: "checkout-to-inventory",
      pathwayId: "checkout-processing",
      title: messages.narrative.inventoryDelayed,
      impact: {
        level: "medium",
        summary: messages.narrative.inventoryImpact,
        affectedEntityIds: ["inventory-service"],
        affectedClusterIds: ["transactions"],
        affectedRouteIds: ["checkout-to-inventory"],
        affectedPathwayIds: ["checkout-processing"],
      },
    },
    {
      id: "mixed-payment-authorized",
      kind: "stage-completed",
      status: "success",
      atMs: 600,
      durationMs: 700,
      entityId: "payment-service",
      clusterId: "transactions",
      routeId: "payment-to-payment-provider",
      pathwayId: "checkout-processing",
      title: messages.narrative.paymentAuthorized,
    },
    {
      id: "mixed-order-published",
      kind: "route-transmission",
      status: "active",
      atMs: 1_500,
      durationMs: 300,
      entityId: "event-bus",
      clusterId: "platform",
      routeId: "orders-to-event-bus",
      pathwayId: "async-fulfillment",
      title: messages.narrative.orderPublished,
    },
    {
      id: "mixed-shipping-processing",
      kind: "stage-processing",
      status: "success",
      atMs: 1_800,
      durationMs: 800,
      entityId: "shipping-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-shipping",
      pathwayId: "async-fulfillment",
      title: messages.narrative.shippingProcessing,
    },
    {
      id: "mixed-notification-failed",
      kind: "failure-raised",
      status: "error",
      atMs: 1_800,
      durationMs: 500,
      entityId: "notification-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-notification",
      pathwayId: "async-fulfillment",
      title: messages.narrative.notificationFailed,
      impact: {
        level: "low",
        summary: messages.narrative.notificationImpact,
        affectedEntityIds: ["notification-service"],
        affectedClusterIds: ["fulfillment"],
        affectedRouteIds: ["event-bus-to-notification"],
        affectedPathwayIds: ["async-fulfillment"],
      },
    },
    {
      id: "mixed-execution-completed",
      kind: "execution-completed",
      status: "warning",
      atMs: 2_600,
      entityId: "orders-service",
      title: messages.narrative.executionCompleted,
    },
  ],
  "degraded-success",
);

export const mixedScenario = {
  id: "mixed",
  state: {
      clusters: { transactions: "warning", fulfillment: "warning", platform: "active" },
      entities: {
        "inventory-service": "warning",
        "notification-service": "error",
        "payment-service": "success",
        "shipping-service": "success",
        "event-bus": "active",
      },
      routes: {
        "checkout-to-inventory": "warning",
        "event-bus-to-notification": "error",
      },
      pathways: { "checkout-processing": "warning", "async-fulfillment": "warning" },
      activity: {
        "inventory-service": 0.95,
        "notification-service": 1,
        "shipping-service": 0.9,
        "event-bus": 1,
      },
    },
  createRuntime: createMixedRuntime,
} as const satisfies ShowcaseScenarioDefinition;
