import type { NeuralCoreRuntimeInput } from "neural-system-ui";

import type { ShowcaseMessages } from "../../i18n/showcase-i18n.types";
import { createShowcaseRuntime } from "./showcase-runtime.factory";
import type { ShowcaseScenarioDefinition } from "./showcase-scenario.types";

const createNormalRuntime = (messages: ShowcaseMessages): NeuralCoreRuntimeInput => createShowcaseRuntime(
  "normal",
  messages,
  3_900,
  [
    {
      id: "normal-request-received",
      kind: "request-received",
      status: "processing",
      atMs: 0,
      durationMs: 300,
      entityId: "api-gateway",
      clusterId: "experience",
      routeId: "web-app-to-api-gateway",
      pathwayId: "customer-request",
      title: messages.narrative.requestReceived,
    },
    {
      id: "normal-authentication-completed",
      kind: "stage-completed",
      status: "success",
      atMs: 300,
      durationMs: 300,
      entityId: "authentication-service",
      clusterId: "experience",
      routeId: "api-gateway-to-authentication",
      title: messages.narrative.authenticationCompleted,
    },
    {
      id: "normal-checkout-started",
      kind: "stage-entered",
      status: "processing",
      atMs: 600,
      durationMs: 500,
      entityId: "checkout-service",
      clusterId: "commerce",
      routeId: "api-gateway-to-checkout",
      pathwayId: "customer-request",
      title: messages.narrative.checkoutStarted,
    },
    {
      id: "normal-inventory-reserved",
      kind: "stage-completed",
      status: "success",
      atMs: 1_100,
      durationMs: 450,
      entityId: "inventory-service",
      clusterId: "transactions",
      routeId: "checkout-to-inventory",
      pathwayId: "checkout-processing",
      title: messages.narrative.inventoryReserved,
    },
    {
      id: "normal-payment-authorized",
      kind: "stage-completed",
      status: "success",
      atMs: 1_550,
      durationMs: 650,
      entityId: "payment-service",
      clusterId: "transactions",
      routeId: "payment-to-payment-provider",
      pathwayId: "checkout-processing",
      title: messages.narrative.paymentAuthorized,
    },
    {
      id: "normal-order-created",
      kind: "stage-completed",
      status: "success",
      atMs: 2_200,
      durationMs: 450,
      entityId: "orders-service",
      clusterId: "commerce",
      routeId: "checkout-to-orders",
      pathwayId: "order-persistence",
      title: messages.narrative.orderCreated,
    },
    {
      id: "normal-order-persisted",
      kind: "stage-completed",
      status: "success",
      atMs: 2_650,
      durationMs: 300,
      entityId: "primary-database",
      clusterId: "platform",
      routeId: "orders-to-primary-database",
      pathwayId: "order-persistence",
      title: messages.narrative.orderPersisted,
    },
    {
      id: "normal-order-published",
      kind: "route-transmission",
      status: "active",
      atMs: 2_950,
      durationMs: 250,
      entityId: "event-bus",
      clusterId: "platform",
      routeId: "orders-to-event-bus",
      pathwayId: "async-fulfillment",
      title: messages.narrative.orderPublished,
    },
    {
      id: "normal-shipping-processing",
      kind: "stage-processing",
      status: "processing",
      atMs: 3_200,
      durationMs: 600,
      entityId: "shipping-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-shipping",
      pathwayId: "async-fulfillment",
      title: messages.narrative.shippingProcessing,
    },
    {
      id: "normal-notification-processing",
      kind: "stage-processing",
      status: "processing",
      atMs: 3_200,
      durationMs: 600,
      entityId: "notification-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-notification",
      pathwayId: "async-fulfillment",
      title: messages.narrative.notificationProcessing,
    },
    {
      id: "normal-execution-completed",
      kind: "execution-completed",
      status: "success",
      atMs: 3_800,
      entityId: "orders-service",
      title: messages.narrative.executionCompleted,
    },
  ],
  "success",
);

export const normalScenario = {
  id: "normal",
  state: {},
  createRuntime: createNormalRuntime,
} as const satisfies ShowcaseScenarioDefinition;
