import type { NeuralCoreRuntimeInput } from "neural-system-ui";

import type { ShowcaseMessages } from "../../i18n/showcase-i18n.types";
import { createShowcaseRuntime } from "./showcase-runtime.factory";
import type { ShowcaseScenarioDefinition } from "./showcase-scenario.types";

const createRealtimeRuntime = (messages: ShowcaseMessages): NeuralCoreRuntimeInput => createShowcaseRuntime(
  "realtime",
  messages,
  3_100,
  [
    {
      id: "realtime-request-received",
      kind: "request-received",
      status: "processing",
      atMs: 0,
      durationMs: 500,
      entityId: "api-gateway",
      clusterId: "experience",
      routeId: "web-app-to-api-gateway",
      pathwayId: "customer-request",
      title: messages.narrative.requestReceived,
    },
    {
      id: "realtime-cart-validated",
      kind: "stage-completed",
      status: "success",
      atMs: 500,
      durationMs: 700,
      entityId: "cart-service",
      clusterId: "commerce",
      routeId: "checkout-to-cart",
      pathwayId: "checkout-processing",
      title: messages.narrative.cartValidated,
    },
    {
      id: "realtime-inventory-reserved",
      kind: "stage-completed",
      status: "success",
      atMs: 500,
      durationMs: 700,
      entityId: "inventory-service",
      clusterId: "transactions",
      routeId: "checkout-to-inventory",
      pathwayId: "checkout-processing",
      title: messages.narrative.inventoryReserved,
    },
    {
      id: "realtime-fraud-approved",
      kind: "stage-completed",
      status: "success",
      atMs: 500,
      durationMs: 700,
      entityId: "fraud-detection-service",
      clusterId: "transactions",
      routeId: "checkout-to-fraud-detection",
      pathwayId: "checkout-processing",
      title: messages.narrative.fraudApproved,
    },
    {
      id: "realtime-payment-authorized",
      kind: "stage-completed",
      status: "success",
      atMs: 500,
      durationMs: 700,
      entityId: "payment-service",
      clusterId: "transactions",
      routeId: "checkout-to-payment",
      pathwayId: "checkout-processing",
      title: messages.narrative.paymentAuthorized,
    },
    {
      id: "realtime-order-created",
      kind: "stage-completed",
      status: "success",
      atMs: 1_200,
      durationMs: 300,
      entityId: "orders-service",
      clusterId: "commerce",
      routeId: "checkout-to-orders",
      pathwayId: "order-persistence",
      title: messages.narrative.orderCreated,
    },
    {
      id: "realtime-order-persisted",
      kind: "stage-completed",
      status: "success",
      atMs: 1_500,
      durationMs: 200,
      entityId: "primary-database",
      clusterId: "platform",
      routeId: "orders-to-primary-database",
      pathwayId: "order-persistence",
      title: messages.narrative.orderPersisted,
    },
    {
      id: "realtime-order-published",
      kind: "route-transmission",
      status: "active",
      atMs: 1_700,
      durationMs: 300,
      entityId: "event-bus",
      clusterId: "platform",
      routeId: "orders-to-event-bus",
      pathwayId: "async-fulfillment",
      title: messages.narrative.orderPublished,
    },
    {
      id: "realtime-shipping-fan-out",
      kind: "route-transmission",
      status: "processing",
      atMs: 2_000,
      durationMs: 900,
      entityId: "shipping-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-shipping",
      pathwayId: "async-fulfillment",
      title: messages.narrative.shippingProcessing,
    },
    {
      id: "realtime-notification-fan-out",
      kind: "route-transmission",
      status: "processing",
      atMs: 2_000,
      durationMs: 900,
      entityId: "notification-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-notification",
      pathwayId: "async-fulfillment",
      title: messages.narrative.notificationProcessing,
    },
    {
      id: "realtime-execution-completed",
      kind: "execution-completed",
      status: "success",
      atMs: 2_900,
      entityId: "orders-service",
      title: messages.narrative.executionCompleted,
    },
  ],
  "success",
);

export const realtimeScenario = {
  id: "realtime",
  state: {
      clusters: {
        commerce: "active",
        transactions: "active",
        fulfillment: "processing",
        platform: "active",
      },
      entities: {
        "checkout-service": "processing",
        "orders-service": "processing",
        "event-bus": "active",
        "shipping-service": "processing",
        "notification-service": "processing",
      },
      pathways: {
        "customer-request": "active",
        "checkout-processing": "active",
        "order-persistence": "active",
        "async-fulfillment": "processing",
      },
      activity: {
        "api-gateway": 1,
        "checkout-service": 1,
        "orders-service": 1,
        "event-bus": 1,
        "shipping-service": 1,
        "notification-service": 1,
      },
    },
  createRuntime: createRealtimeRuntime,
} as const satisfies ShowcaseScenarioDefinition;
