import type { NeuralCoreRuntimeInput } from "neural-system-ui";

import type { ShowcaseMessages } from "../../i18n/showcase-i18n.types";
import { createShowcaseRuntime } from "./showcase-runtime.factory";
import type { ShowcaseScenarioDefinition } from "./showcase-scenario.types";

const createWarningRuntime = (messages: ShowcaseMessages): NeuralCoreRuntimeInput => createShowcaseRuntime(
  "warning",
  messages,
  4_800,
  [
    {
      id: "warning-request-received",
      kind: "request-received",
      status: "processing",
      atMs: 0,
      durationMs: 400,
      entityId: "api-gateway",
      clusterId: "experience",
      routeId: "web-app-to-api-gateway",
      pathwayId: "customer-request",
      title: messages.narrative.requestReceived,
    },
    {
      id: "warning-checkout-started",
      kind: "stage-entered",
      status: "processing",
      atMs: 400,
      durationMs: 500,
      entityId: "checkout-service",
      clusterId: "commerce",
      routeId: "api-gateway-to-checkout",
      pathwayId: "customer-request",
      title: messages.narrative.checkoutStarted,
    },
    {
      id: "warning-inventory-delayed",
      kind: "warning-raised",
      status: "warning",
      atMs: 900,
      durationMs: 1_500,
      entityId: "inventory-service",
      clusterId: "transactions",
      routeId: "checkout-to-inventory",
      pathwayId: "checkout-processing",
      title: messages.narrative.inventoryDelayed,
      metrics: [
        {
          id: "inventory-latency",
          name: messages.metrics.latency,
          value: 1_500,
          unit: "ms",
          status: "warning",
          trend: "up",
        },
      ],
      impact: {
        level: "medium",
        summary: messages.narrative.inventoryImpact,
        affectedEntityIds: ["inventory-service"],
        affectedClusterIds: ["transactions"],
        affectedRouteIds: ["checkout-to-inventory"],
        affectedPathwayIds: ["checkout-processing"],
      },
    },
    {
      id: "warning-payment-authorized",
      kind: "stage-completed",
      status: "success",
      atMs: 2_400,
      durationMs: 700,
      entityId: "payment-service",
      clusterId: "transactions",
      routeId: "payment-to-payment-provider",
      pathwayId: "checkout-processing",
      title: messages.narrative.paymentAuthorized,
    },
    {
      id: "warning-order-created",
      kind: "stage-completed",
      status: "success",
      atMs: 3_100,
      durationMs: 600,
      entityId: "orders-service",
      clusterId: "commerce",
      routeId: "checkout-to-orders",
      pathwayId: "order-persistence",
      title: messages.narrative.orderCreated,
    },
    {
      id: "warning-order-published",
      kind: "route-transmission",
      status: "active",
      atMs: 3_700,
      durationMs: 350,
      entityId: "event-bus",
      clusterId: "platform",
      routeId: "orders-to-event-bus",
      pathwayId: "async-fulfillment",
      title: messages.narrative.orderPublished,
    },
    {
      id: "warning-shipping-processing",
      kind: "stage-processing",
      status: "processing",
      atMs: 4_050,
      durationMs: 650,
      entityId: "shipping-service",
      clusterId: "fulfillment",
      routeId: "event-bus-to-shipping",
      pathwayId: "async-fulfillment",
      title: messages.narrative.shippingProcessing,
    },
    {
      id: "warning-execution-completed",
      kind: "execution-completed",
      status: "warning",
      atMs: 4_700,
      entityId: "orders-service",
      title: messages.narrative.executionCompleted,
    },
  ],
  "degraded-success",
);

export const warningScenario = {
  id: "warning",
  state: {
      clusters: { transactions: "warning" },
      entities: { "inventory-service": "warning" },
      routes: { "checkout-to-inventory": "warning" },
      pathways: { "checkout-processing": "warning" },
      activity: { "inventory-service": 1 },
    },
  createRuntime: createWarningRuntime,
} as const satisfies ShowcaseScenarioDefinition;
